### ISSUE TITLE
error with angular2-beta11

### ISSUE THREAD

**Issue by filoucpp** [BTMorton/angular2-grid#57] opened 2016-03-21 19:07 UTC
hi!

I'm getting an error with the latest angular2-beta11 version:

`EXCEPTION: TypeError: core_1.View is not a function`

It can be easily fixed by changing NgGrid.ts file from this

![screen shot 2016-03-21 at 2 06 11 pm](https://cloud.githubusercontent.com/assets/17276605/13930743/28e9b4f8-ef6e-11e5-82be-0b2ae27cf8a0.png)

into that

![screen shot 2016-03-21 at 2 06 33 pm](https://cloud.githubusercontent.com/assets/17276605/13930747/2e1d1db6-ef6e-11e5-9574-c1ffbcb022a4.png)

Thanks for the hard work!!

**Comment by BTMorton** [comment] 2016-03-21 20:23
Dupe of #53. Will get on it ASAP, keep an eye there for updates :)

**Closed by BTMorton** 2016-03-21 20:23 UTC

**Comment by filoucpp** [comment] 2016-03-21 21:21
sorry for the duplicate, thanks a lot!
