### ISSUE TITLE
I can't get it up and running...?!

### ISSUE THREAD

**Issue by gopchi** [BTMorton/angular2-grid#188] opened 2017-01-25 21:15 UTC
Hi guys,

I just installed everything as it is said, but there is an error that occurs - NgGrid - cannot find module NgGrid.

What am I supposed to do to make it work? I really need the functionality of this module.

Could you help and give detailed instructions how to make it work without system-js. I am using the angular-cli.

Thanks!

**Comment by NotBad4U** [comment] 2017-01-25 21:20
#179 I think you have the same problem. 
We found a workaround (see the issue) until @BTMorton fix the bug. 
The problem is angular evolve very quickly (with major update like the management of module) and all the libs are not up to date with the latest version.

**Comment by gopchi** [comment] 2017-01-25 21:32
@NotBad4U  Thanks a lot, mate! Could you tell me how can I configure the grid items, because when I use an empty directive as [(ngGridItem)] it throws me an error like this:

`Parser Error: Unexpected token = at column 1 in [=$event]`

From where should I load the configs?

**Comment by NotBad4U** [comment] 2017-01-25 21:50
Add the import statement `import { NgGridConfig, NgGridItemConfig } from "./angular2-grid/interfaces/INgGrid";` (with the path relative to where is your angular2-grid copy)
and to all of your "Box" set the config field: 

```
this.boxes[i].config = _generateDefaultItemConfig(); 

private _generateDefaultItemConfig(): NgGridItemConfig {
		return { 'dragHandle': '.handle', 'col': 1, 'row': 1, 'resizable': true, 'minWidth': 10, 'minHeight': 10, 'sizex': 1, 'sizey': 1 };
}

```
See the demo provide or the code in `/src/app.component.ts`. And take a look at the readme for more details of how  to configure in details the grid and the grid items.

**Comment by gopchi** [comment] 2017-01-25 23:42
I got it working! Thanks a lot! Just one more question: Is there a possibility to define the Items in a div and then another div with predefined width and height to be the gridContainer. And then to drag and drop the items into the container div. 

I tried doing it with jQuery UI, but unfortunately, I could make it with it, because it was giving me an error of type .draggable() is not a function.

Would you suggest something regarding this?

**Comment by BTMorton** [comment] 2017-01-26 01:30
There currently isn't support for having an external drop target. It's been requested before if you look through the other issues. I'm closing this now, as the main issue should be sorted.

**Closed by BTMorton** 2017-01-26 01:30 UTC
