### ISSUE TITLE
Option to make grid item collapse

### ISSUE THREAD

**Issue by Franki1986** [BTMorton/angular2-grid#202] opened 2017-02-15 10:58 UTC
Hi!
Could there be an option to collapse or expand a gridItem.
At the moment the space of a row width is always reserved.

**Comment by BTMorton** [comment] 2017-03-05 12:18
I think this is a duplicate of #206 where I just gave a response. If you had a different use case, feel free to reopen.

**Closed by BTMorton** 2017-03-05 12:18 UTC
