### ISSUE TITLE
onload event handling missing for limit_to_screen

### ISSUE THREAD

**Issue by Ketec** [BTMorton/angular2-grid#204] opened 2017-02-20 13:43 UTC
Currently it only resizes/moves "widgets" when you resize the screen - but this does not apply on first load - so the "widgets" can end up hidden (overflow:hidden) until you resize.

Current workaround was for me to:
```
  @ViewChild(NgGrid)
  private ngGrid:NgGrid;

  constructor() {
    window.onload = (e) =>
    {
      this.ngGrid.resizeEventHandler(e);
    };
  }
```

**Comment by BTMorton** [comment] 2017-03-05 12:18
Closing as duplicate of #199

**Closed by BTMorton** 2017-03-05 12:18 UTC
